name: Courier_API-CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    braches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

     
        
      
      - name: Install Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      

      - name: Run migrations
        env:
            DB_URL: ${{ DB_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
