name: Courier_API-CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    braches: [ main ]

env:
  DB_URL: ${{ secrets.DB_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
       
     
        
      
      - name: Install Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      

      - name: Run migrations
        
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test


  deploy:
    name: Deploy to Digitalocean 
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to Digitalocean
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
    
          script: |
            cd /courier_api
            git pull
            docker-compose down
            docker-compose up --build
  


